PLAYER_TILE = 0
ENEMY_TILE = 1
EXIT_TILE = 2
KEY_TILE = 3
CHEST_TILE = 4
WALL_TILE = 5
FLOOR_TILE = 6
TRAP_TILE = 7

DUNGEON_HEIGHT = 11
DUNGEON_WIDTH = 14
HOW_MUCH_WALLS_WHERE_PASS = 4
HOW_MANY_PASSES_MAX = 2