PLAYER_TILE = 0
ENEMY_TILE = 1
EXIT_TILE = 2
KEY_TILE = 3
CHEST_TILE = 4
WALL_TILE = 5
FLOOR_TILE = 6
TRAP_TILE = 7

x_coord = 0
y_coord = 1

DUNGEON_HEIGHT = 11
DUNGEON_WIDTH = 14
HOW_MUCH_WALLS_WHERE_PASS = 4
HOW_MANY_PASSES_MAX = 2

MAX_ENEMY = 7
MIN_ENEMY = 3
MAX_TRAPS = 6
MIN_TRAPS = 0
MAX_CHESTS = 3
MIN_CHESTS = 1
AMT_KEY = 1

BASE_CHANCE = 1

DEFAULT_FONT = '\033[32m'
START_FIGHT_MESSAGE_FONT = '\033[1;31m'
PLAYER_HP_FONT = '\033[2;32m'
ENEMY_HP_FONT = '\033[1;31m'
PLAYER_INITIATIVE_FONT = '\033[94m'
ENEMY_INITIATIVE_FONT = '\u001b[34m'

PLAYER_ICON = '\033[5;32m'
ENEMY_ICON = '\033[1;31m'
EXIT_ICON = '\033[2;32m'
KEY_ICON = '\033[2;32m'
CHEST_ICON = '\033[2;33m'
WALL_ICON = '\033[0;37m'
FLOOR_ICON = '\033[0;37m'
TRAP_ICON = '\033[2;31m'

EXIT_COMMANDS = ['exit', 'EXIT', 'QUIT', 'Q', 'q',]
COMBAT_COMMANDS = ['a', 'd', 'i', 'h']
TRAP_COMMANDS = ['1', '2']
DOOR_INTERACTION_COMMANDS = ['1', '2', '3']

ENTITY_NAME = 0
ENTITY_HP = 1
ENTITY_INITIATIVE = 2
ENTITY_DAMAGE = 3
ENTITY_MISS_CHANCE = 4
ENTITY_TOXICITY = 5
PLAYER_ITEM_DEFUSAL_KIT = 6
PLAYER_ITEM_KEY = 7

ITEM_NOTHING = 0
ITEM_DEFUSAL_KIT = 1

NAME_ENEMY_PUNK = 'Панк'
NAME_ENEMY_SYNTH_HOUND = 'Синт. гончая'
NAME_ENEMY_GLITCH_BUTCHER = 'Мясник'
NAME_ENEMY_PSY_CODER = 'Пси-кодер'

STATE_OF_ADVENTURING_FIGHT = 'is_fight'
STATE_OF_ADVENTURING_EXIT = 'exit'
STATE_OF_ADVENTURING_EXFILL = 'exfill'

COMMAND_MOVE_UP = 'w'
COMMAND_MOVE_LEFT = 'a'
COMMAND_MOVE_DOWN = 's'
COMMAND_MOVE_RIGHT = 'd'